openapi: 3.0.3
info:
  version: 1.0.0
  title: shortest-path
  description: >
    # Service overview:
    TODO

paths:
  /country/routing:
    get:
      summary: 'Calculate path for selected countries'
      operationId: 'CountryRouting'
      description: >
        ## TODO
      parameters:
        - in: header
          name: headers
          schema:
            $ref: '#/components/schemas/Headers'
          required: true
        - in: query
          name: from
          required: true
          description: The starting point.
          schema:
            type: string
        - in: query
          name: to
          required: true
          description: The destination point.
          schema:
            type: string
        - in: query
          name: countryIdentifierType
          description: Interpretation method for from/to parameters
          required: false
          schema:
            $ref: '#/components/schemas/CountryIdentifierTypeDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response400'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response404'

  /country/{countryCode}:
    get:
      summary: 'Calculate path for selected countries'
      operationId: 'CountryDetails'
      description: >
        ## TODO
      parameters:
        - in: header
          name: headers
          required: true
          schema:
            $ref: '#/components/schemas/Headers'
        - in: path
          name: countryCode
          required: true
          schema:
            $ref: '#/components/schemas/CountryCode'
        - in: query
          name: countryIdentifierType
          required: false
          description: Interpretation method for from/to parameters
          schema:
            $ref: '#/components/schemas/CountryIdentifierTypeDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDetailsDTO'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response400'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response404'

  /trip:
    post:
      summary: 'Save trip'
      operationId: 'saveTrip'
      description: >
        ## TODO
      parameters:
        - in: header
          name: headers
          schema:
            $ref: '#/components/schemas/Headers'
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTripDTO'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response400'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response404'
    get:
      summary: 'Get all trips'
      operationId: 'getAll'
      description: >
        ## TODO
      parameters:
        - in: header
          name: headers
          schema:
            $ref: '#/components/schemas/Headers'
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseTripDTO'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response400'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response404'

components:
  schemas:
    Headers:
      type: object
      additionalProperties:
        type: string

    CountryIdentifierTypeDTO:
      type: string
      default: ISO_CODE
      description: Interpretation method for from/to parameters
      enum:
        - ISO_CODE
        - CCA_3
        - NAME

    CountryDetailsDTO:
      type: object
      properties:
        name:
          type: string
          maxLength: 128
        region:
          type: string
          maxLength: 128
        isoCode:
          type: string
          maxLength: 2
          minLength: 2
        countryCode:
          $ref: '#/components/schemas/CountryCode'
        coordinates:
          type: array
          items:
            type: number
            format: float
      required:
        - name
        - region
        - isoCode
        - countryCode
        - coordinates
    RequestTripDTO:
      type: object
      properties:
        name:
          type: string
          maxLength: 128
        countries:
          $ref: '#/components/schemas/CountriesList'
      required:
        - name
        - countries
    ResponseTripDTO:
      type: object
      properties:
        name:
          type: string
          maxLength: 128
        countries:
          $ref: '#/components/schemas/CountriesList'
        createdAt:
          type: string
          format: date
      required:
        - name
        - countries
        - createdAt

    CountriesList:
      type: string
      pattern: '^[A-Z]{3}(,[A-Z]{3})*$'
      example: "USA,GBR,CAN"

    CountryCode:
      type: string
      maxLength: 3
      minLength: 3
      example: "USA"

    Response400:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
    Response404:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message